#バージョン名は不要
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db:/var/lib/mysql:delegated"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"

  api:
    #ベースイメージとなるDockerFileを指定
    build:
      context: ./api
      #環境変数をDockerFileにわたす
      args:
        WORKDIR: $WORKDIR
    entrypoint: /usr/bin/entrypoint.sh
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"      
      BASE_URL: "http://localhost:$API_PORT" 
      # api\config\initializers\user_auth.rbの環境変数として追加
    volumes:
      - ./api:/$WORKDIR
      #apiサービス起動前にDBを起動という関係
    depends_on:
      - db
    #公開用ポートを指定
    #公開したいポート番号：デフォルトのコンテナポート
    ports:
      - "$API_PORT:3000"      
    tty: true

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT" # 追加           
    volumes:
      #ホストからコンテナの読み取りを最適化するためcacheオプションを記載
      - ./front:/app:cached
      #node_moduleのボリュームはコンテナ上に置かないと起動が重くなる
      - nuxt_node_modules:/app/node_modules
    ports:
      - "$FRONT_PORT:3000"
      #Nuxt3のホットリロードのポート
      - "24678:24678"
    #tty（仮想端末）のプロセスを起動してあげることでコンテナの正常終了を伏せぐ
    tty: true
    environment:
      - port=$FRONT_PORT   
      #ホットリロード可能にするため追記 
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    #npmで起動するようにしてみる
    command: sh -c "npm run dev"
volumes:
  nuxt_node_modules:
